### PR TITLE
Bug/loopcontinue only when recievingresponse

### LINKED ISSUE #216: request concatination
in status loop only send new request when previous request returned

### PR DESCRIPTION
**Pull request by thomashaenig**
closes #216

### CODE REVIEW

File: src/ser-ext-ondemandDirective.ts [hunk 1]
```diff
@@ -380,8 +382,14 @@ class OnDemandController implements ng.IController {
         if (typeof (intervalTime) === "undefined") {
             intervalTime = 5000;
         }
-        this.interval = window.setInterval(() => {
-            this.getStatus(this.taskId);
+        this.interval = window.setInterval(async () => {
+            this.timeoutResponseCounter++;
+            if (this.timeoutResponseRevieved || this.timeoutResponseCounter > 10) {
+                this.timeoutResponseRevieved = false;
```
Comment (r-hannuschka) [inline src/ser-ext-ondemandDirective.ts]: should be redundant since u set this to false and 1 line later to response from promise, could removed

File: src/ser-ext-ondemandDirective.ts [hunk 2]
```diff
@@ -660,74 +668,77 @@ class OnDemandController implements ng.IController {
...
-                        let distributeObject: IDistribute = JSON.parse(statusObject.distribute);
+            this.logger.debug("statusObject.Status", statusObject.status);
 
-                        this.links = [];
-                        for (const hubResult of distributeObject.hubResults) {
-                            if (hubResult.success) {
-                                this.links.push(`${this.host}${hubResult.link}`)
-                            }
+            switch (statusObject.status) {
+                case -2:
```
Comment (r-hannuschka) [inline src/ser-ext-ondemandDirective.ts]: please implement enum for status, so it is better to read. Now u know -2 means error but if u come back a half year later the first question will be "What is -2 ?" 

```
export const enum RESPONSE_STATUS {
    ERROR: -2,
    ...
    COMPLETED: 3
}

// and then implement this in switch case
switch (statusObject.status) {
    case ResponseStatus.ERROR: ... break;
```

Comment (thomashaenig) [reply src/ser-ext-ondemandDirective.ts]: is included in new commit

File: src/ser-ext-ondemandDirective.ts (hunk 1 above)
Comment (thomashaenig) [reply src/ser-ext-ondemandDirective.ts]: @r-hannuschka : set false at this point is necessary, because when the response from the getStatus Promise takes a lot of time, it will not enter the getStatus request again
